modLoader="javafml"
loaderVersion="[37,)"
license="LGPL v2.1"
[[mods]]
modId="tutorial"
version="1.0.0"
displayName="Tutorial Mod"
credits="TurtyWurty, McJty"
authors="BWBJustin"
description="Tutorial Mod"